### ISSUE TITLE
LCFIPlus crashes in miniDST workflow for some inputs

### ISSUE THREAD

**Issue by tmadlener** [lcfiplus/LCFIPlus#59]
In the context of the [miniDST workflow](https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/production/MarlinStdRecoMiniDST.xml) we have encountered some issues when the primary vertex collection is empty: iLCSoft/MarlinReco#93. We have a fix available for the underlying problem there (see iLCSoft/MarlinReco#94). However, with that fix in place we run into problems with LCFIPlus, which is run directly after the isolated lepton finding/tagging in the miniDST workflow.

We get a segmentation fault and the following stacktrace:

```
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f68e34644fc in waitpid () from /lib64/libc.so.6
#1  0x00007f68e33e1f62 in do_system () from /lib64/libc.so.6
#2  0x00007f68e2baddd3 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x1d4a570) at /tmp/madlener/spack-stage/spack-stage-root-6.24.00-u7xb6dwwdgx7v3xbdg37tsfvdufauaef/spack-src/core/unix/src/TUnixSystem.cxx:2120
#3  TUnixSystem::StackTrace (this=0x1d4a570) at /tmp/madlener/spack-stage/spack-stage-root-6.24.00-u7xb6dwwdgx7v3xbdg37tsfvdufauaef/spack-src/core/unix/src/TUnixSystem.cxx:2411
#4  0x00007f68e2bb06f5 in TUnixSystem::DispatchSignals (this=0x1d4a570, sig=kSigSegmentationViolation) at /tmp/madlener/spack-stage/spack-stage-root-6.24.00-u7xb6dwwdgx7v3xbdg37tsfvdufauaef/spack-src/core/unix/src/TUnixSystem.cxx:3649
#5  <signal handler called>
#6  0x00007f68bc717e4a in lcfiplus::algoEtc::SimpleSecMuonFinder(lcfiplus::Track const*, double, double, double, double, double, double, double, double, double, lcfiplus::Vertex const*) () from /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep/install/spackages_nfs_root/lcfiplus/0.10/x86_64-centos7-gcc8.3.0-opt/b7t3p7hze6ek467ftef3whqcagxvrnuy/lib/libLCFIPlus.so
#7  0x00007f68bc6be1da in lcfiplus::JetFinder::prerun(std::vector<lcfiplus::Track const*, std::allocator<lcfiplus::Track const*> > const&, std::vector<lcfiplus::Neutral const*, std::allocator<lcfiplus::Neutral const*> > const&, std::vector<lcfiplus::Vertex const*, std::allocator<lcfiplus::Vertex const*> > const&, int*) () from /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep/install/spackages_nfs_root/lcfiplus/0.10/x86_64-centos7-gcc8.3.0-opt/b7t3p7hze6ek467ftef3whqcagxvrnuy/lib/libLCFIPlus.so
#8  0x00007f68bc73bb19 in lcfiplus::JetClustering::process() () from /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep/install/spackages_nfs_root/lcfiplus/0.10/x86_64-centos7-gcc8.3.0-opt/b7t3p7hze6ek467ftef3whqcagxvrnuy/lib/libLCFIPlus.so
#9  0x00007f68bc6d6ae2 in LcfiplusProcessor::processEvent(EVENT::LCEvent*) () from /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep/install/spackages_nfs_root/lcfiplus/0.10/x86_64-centos7-gcc8.3.0-opt/b7t3p7hze6ek467ftef3whqcagxvrnuy/lib/libLCFIPlus.so
#10 0x00007f68e56c03c1 in marlin::ProcessorMgr::processEvent (this=0x1dfa140, evt=0x17571d00) at /tmp/madlener/spack-stage/spack-stage-marlin-1.17.1-4rg3d777ujzvtjwpmluuhg4lgc6n2ik6/spack-src/source/src/ProcessorMgr.cc:494
#11 0x00007f68e4ffefa1 in SIO::SIOReader::processEvent(std::shared_ptr<EVENT::LCEvent>) () from /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep/install/spackages_nfs_root/lcio/2.16.1/x86_64-centos7-gcc8.3.0-opt/nqt55lk5fmwwer334skcjgjcihnbghmr/lib/liblcio.so.2.16
#12 0x00007f68e500cf48 in MT::LCReader::readStream(std::unordered_set<MT::LCReaderListener*, std::hash<MT::LCReaderListener*>, std::equal_to<MT::LCReaderListener*>, std::allocator<MT::LCReaderListener*> > const&, int) () from /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep/install/spackages_nfs_root/lcio/2.16.1/x86_64-centos7-gcc8.3.0-opt/nqt55lk5fmwwer334skcjgjcihnbghmr/lib/liblcio.so.2.16
#13 0x00007f68e500d747 in MT::LCReader::readStream(MT::LCReaderListener*, int) () from /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep/install/spackages_nfs_root/lcio/2.16.1/x86_64-centos7-gcc8.3.0-opt/nqt55lk5fmwwer334skcjgjcihnbghmr/lib/liblcio.so.2.16
#14 0x000000000040ae37 in main (argc=<optimized out>, argv=<optimized out>) at /tmp/madlener/spack-stage/spack-stage-marlin-1.17.1-4rg3d777ujzvtjwpmluuhg4lgc6n2ik6/spack-src/source/src/Marlin.cc:467
===========================================================
```

I had a quick look into the `SimpleSecMuonFinder` and the `JetFinder::prerun`, but I couldn't find anything obvious there. Could you have a look and see what the problem is in this case? We can also provide the necessary inputs to reproduce the above crash. 

NOTE: The stacktrace above does not use a central ilcsoft installation, but we get a segmentation violation also if we use the v02-02-02 release (even if we do not get a stacktrace with that).

**Comment by ryonamin** [comment]
@tmadlener
Could you let us know what sample to be used to reproduce the problem? It would be helpful to identify the cause.
Thank you in advance.

**Comment by ryonamin** [comment]
@tmadlener 
Thank you for your input. I was able to reproduce the problem.
I found that LCFIPlus tried to access the null pointer for primary vertex when no primary vertex was found. So I have made a pull request to make a "practical" or "virtual" vertex that is defined as (0.,0.,0.) with error (0.,0., beam spot size in z) in such special cases.
